config/routes.rb
RailsDciExample::Application.routes.draw do
  resources :documents

  devise_for :users

end

app/models/document.rb
class Document < ActiveRecord::Base
  attr_accessible :contect, :title, :user_id

  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  
  has_many :documents, :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :authenticate_user!
end

app/controllers/documents_controller.rb
require "documents/all_context" 
require "documents/create_context" 
require "documents/get_context" 
require "documents/update_context" 
require "documents/destroy_context" 

class DocumentsController < ApplicationController
  def index
    @documents = Documents::AllContext.new(current_user).execute
  end

  def show
    @document = Documents::GetContext.new(current_user, params[:id]).execute
  end

  def new
    @document = Documents::BuildContext.new(current_user).execute
  end

  def edit
    @document = Documents::GetContext.new(current_user).execute
  end

  def create
    @document = Documents::CreateContext.new(current_user, params[:document]).execute

    if @document.valid?
      redirect_to @document, notice: 'Document was successfully created.'
    else
      render action: "new"
    end
  end

  def update
    @document = Documents::UpdateContext.new(current_user, params[:id], params[:document]).execute

    if @document.valid?
      redirect_to @document, notice: 'Document was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @document = Documents::DestroyContext.new(current_user, params[:id]).execute

    redirect_to documents_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_form.html.erb
<%= form_for(@document) do |f| %>
  <% if @document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
      <% @document.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :contect %><br />
    <%= f.text_area :contect %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/documents/edit.html.erb
<h1>Editing document</h1>

<%= render 'form' %>

<%= link_to 'Show', @document %> |
<%= link_to 'Back', documents_path %>

app/views/documents/index.html.erb
<h1>Listing documents</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Contect</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @documents.each do |document| %>
  <tr>
    <td><%= document.title %></td>
    <td><%= document.contect %></td>
    <td><%= link_to 'Show', document %></td>
    <td><%= link_to 'Edit', edit_document_path(document) %></td>
    <td><%= link_to 'Destroy', document, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Document', new_document_path %>

app/views/documents/new.html.erb
<h1>New document</h1>

<%= render 'form' %>

<%= link_to 'Back', documents_path %>

app/views/documents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @document.title %>
</p>

<p>
  <b>Contect:</b>
  <%= @document.contect %>
</p>


<%= link_to 'Edit', edit_document_path(@document) %> |
<%= link_to 'Back', documents_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsDciExample</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>